export default [
  {
    firstName: "Meghan",
    lastName: "Bibb",
    linkedIn: "https://www.linkedin.com/in/meghanbibb/",
    github: "",
    title: "C4C President",
    major: "Computer Science",
    class: "Senior",
    image: require("assets/img/meghan_profile.jpeg"),
  },
  {
    firstName: "Brookylnn",
    lastName: "Stone",
    linkedIn: "",
    github: "",
    title: "C4C Vice President",
    major: "Computer Science",
    class: "Junior",
  },
  {
    firstName: "Zachery",
    lastName: "Scherer",
    linkedIn: "",
    github: "",
    title: "Wacode Coordinator",
    major: "Computer Science",
    class: "Sophomore",
  },
  {
    firstName: "Alessandra",
    lastName: "Rodriguez",
    linkedIn: "",
    github: "",
    title: "Marketing",
    major: "???",
    class: "???",
  },
  {
    firstName: "Brittany",
    lastName: "Solorio",
    linkedIn: "",
    github: "",
    title: "Corporate Outreach",
    major: "???",
    class: "???",
  },
  {
    firstName: "Matthew",
    lastName: "McCaskill",
    linkedIn: "https://www.linkedin.com/in/matthew-mccaskill/",
    github: "https://github.com/ZekNikZ",
    title: "Event Coordinator",
    major: "Computer Science",
    class: "Junior",
  },
];
