export default [
  {
    firstName: "Meghan",
    lastName: "Bibb",
    linkedIn: "https://www.linkedin.com/in/meghanbibb/",
    github: "https://github.com/MeghanBibb",
    title: "C4C President",
    major: "Computer Science",
    class: "Senior",
    image: require("assets/img/officers/meghan.jpeg"),
  },
  {
    firstName: "Brookylnn",
    lastName: "Stone",
    linkedIn: "https://www.linkedin.com/in/brooklynn-stone/",
    github: "https://github.com/brooklynnStone1",
    title: "C4C Vice President",
    major: "Computer Science",
    class: "Junior",
    image: require("assets/img/officers/brooklynn.jpeg"),
  },
  {
    firstName: "Zachary",
    lastName: "Scherer",
    linkedIn: "https://www.linkedin.com/in/zachary-scherer-27470b183/",
    github: "https://github.com/ScheZach",
    title: "Wacode Coordinator",
    major: "Computer Science",
    class: "Sophomore",
    image: require("assets/img/officers/zachary.jpg"),
  },
  {
    firstName: "Alessandra",
    lastName: "Rodriguez",
    linkedIn: "",
    github: "",
    title: "Marketing",
    major: "Statistics",
    class: "Sophomore",
    image: require("assets/img/officers/alessandra.jpg"),
  },
  {
    firstName: "Brittany",
    lastName: "Solorio",
    linkedIn: "",
    github: "",
    title: "Corporate Outreach",
    major: "Management Information Systems",
    class: "Junior",
    image: require("assets/img/officers/brittany.JPG"),
  },
  {
    firstName: "Matthew",
    lastName: "McCaskill",
    linkedIn: "https://www.linkedin.com/in/matthew-mccaskill/",
    github: "https://github.com/ZekNikZ",
    title: "Event Coordinator",
    major: "Computer Science",
    class: "Junior",
    image: require("assets/img/officers/matthew.jpeg"),
  },
];
